language: generic
sudo: requied

services:
    - docker

before_install:
    - docker build -t hahemsi/multi-container-test -f ./client/Dockerfile.dev ./client
    # we can add more build script to run tests in other projects

script:
    - docker run -e CI=true hahemsi/multi-container-test npm run test -- --coverage
    # run additional tests

after_success:
    - docker build -t hahemsi/multi-client ./client
    - docker build -t hahemsi/multi-nginx ./nginx
    - docker build -t hahemsi/multi-server ./server
    - docker build -t hahemsi/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take all images and push them to docker hub
    - docker push hahemsi/multi-client
    - docker push hahemsi/multi-nginx
    - docker push hahemsi/multi-server
    - docker push hahemsi/multi-worker
    
deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-west-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-west-1-363582733969"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY



